### ISSUE TITLE
Default theme swap icon doesn't correspond to default theme

### ISSUE THREAD

**Issue by 12vanblart** [DavidCouronne/gridsome-starter-blog-vuetify#2]
(This may be only for users that don't have a theme set on their OS)

By default the "Theme swap" button/icon is being set as if the site is in the Light theme, but the theme is being set to dark theme in the vuetify config file (`dark: true`). 

Either the config file should be set to `dark: false` or the button should default to assume the user starts in dark mode (the sun shows). 

![image](https://user-images.githubusercontent.com/16465776/68429373-f28aa880-017b-11ea-93e1-71722323a07d.png)

**Comment by DavidCouronne** [comment]
Hello,

Thanks for reporting. I remove `dark:true`in vuetify.config.js
